### ISSUE TITLE
support for wildcard in parameters to plot

### ISSUE THREAD

**Issue by ntessore** [cmbant/getdist#1]
In glenco/lensed, we have parameter names of the form `object.param`, for example

```
lens.x                x_L
lens.y                y_L
lens.r                r_L
...
source.x              x_S
source.y              y_S
source.r              r_S
...
```

Since the number of parameters can get quite large, it would be great if GetDist supported a wildcard for parameter names to plot, so that we could set for example

```ini
plot_params = lens.*
triangle_params = lens.*
```

instead of manually listing the lens parameters.

**Comment by cmbant** [comment]
Try the latest (with commit a105251b3b)

**Comment by ntessore** [comment]
Works great!
