### ISSUE TITLE
Credit boilerplate

### ISSUE THREAD

**Issue by pkaf** [cmbant/getdist#10]
This is not really an issue, just a query.

I am using getdist extensively in my project and like to provide due credit. Except the github/webpage link, is there any boilerplate credit line that I can provide in my paper?

**Comment by cmbant** [comment]
There's no particular credit line required. Since getdist is part of cosmomc, you can just cite the cosmomc papers.

There is also a DOI for the github repository: https://doi.org/10.5281/zenodo.225727
