### ISSUE TITLE
Finer grids for getdist.densities.DensityND class objects?

### ISSUE THREAD

**Issue by TiankeZhuang** [cmbant/getdist#101]
Hi, I was wondering if I could tune how many grid points I can get for running MCSamples.getRawNDDensityGridData? Currently I get 12 points in each dimension for a 4D density. I tried looking into the analysis_defaults.ini file but couldn't find anything pertaining to ND densities.

If that is not possible, would you happen to know if there is another way to reconstruct the ND likelihood from results of a cobaya run?

**Comment by cmbant** [comment]
You can pass num_bins_ND or set global setting num_bins_ND

**Comment by cmbant** [comment]
Please ask questions on CosmoCoffee.info, this is for bug reports
