### ISSUE TITLE
Question on GetDist + LaTex

### ISSUE THREAD

**Issue by Uendert** [cmbant/getdist#104]
Hi all,

Usually, I follow the example to get a LaTex table:

```
print(samples.getTable().tableTex())
\begin{tabular} { l  c}

 Parameter &  95\% limits\\
\hline
{\boldmath$x_0            $} & $0.0^{+2.6}_{-2.6}         $\\

{\boldmath$x_1            $} & $0.0^{+2.4}_{-2.4}         $\\

{\boldmath$x_2            $} & $0.0^{+2.7}_{-2.7}         $\\

{\boldmath$x_3            $} & $0.0^{+3.1}_{-3.1}         $\\

$z_d                       $ & $27^{+30}_{-20}            $\\
\hline
\end{tabular}
```

However, when one needs to create a LaTex table with multiple probes in each column, this requires generating a new LaTex table for each probe and manually merging them, which can be pretty frustrating!

Does anyone know a more clean way to do that? I imagine it should be possible to merge them at the level of Python objects before turning them into a Latex Table, but I didn't find such a capability.

Just as an illustration, something like `samples1.getTable().tableTex() + samples2.getTable().tableTex()`  would be nice.

All the best,
Uendert

**Comment by cmbant** [comment]
You can also use e.g.
`
types.ResultTable(columns, [samples1.getMargeStats(),samples2.getMargeStats()], **kwargs)`
