### ISSUE TITLE
Excluding a chain when loading samples

### ISSUE THREAD

**Issue by xgarrido** [cmbant/getdist#105]
I'm currently running 4 parallel chains and for obscure reason, one of them is running much slower than the others. So, when loading the samples, I'd like not to use it by specifying its mcmc index. Is there an easy way to do this without removing/renaming the MCMC text file ?

I've dig into the code and see that `loadMCSamples` function actually starts by fetching the MCMC `txt` filenames using the `chainFiles` function. At this level, it is possible to exclude chains by providing a list of indexes with the `chain_exclude` argument (https://github.com/cmbant/getdist/blob/master/getdist/chains.py#L75). Can we imagine adding this `chain_exclude` argument to `loadMCSamples` function ? If yes, I can create a PR for this.

**Comment by cmbant** [comment]
Sure, don't see why not, though may need to check consistent cacheing for loads when that parameter is varied

**Comment by xgarrido** [comment]
Good point. I think using this option implies `no_cache=True` or to generate an hash key encoding the `chain_exclude` value. Something like

```python
hashlib.md5((os.path.abspath(path) + str(chain_exclude)).encode("utf-8")).hexdigest()[:10]
```

But then it's a new `pickle` file...

**Comment by cmbant** [comment]
I guess no_cache True would be fine for this test case
