### ISSUE TITLE
installation issue with python 3.7

### ISSUE THREAD

**Issue by Debabrataadak** [cmbant/getdist#109]
File "setup.py", line 41, in make_app
    os.path.join(file_dir, app_name), dirs_exist_ok=True)
TypeError: copytree() got an unexpected keyword argument 'dirs_exist_ok'

some sources says  'dirs_exist_ok' keyword is used only after python 3.8

**Comment by cmbant** [comment]
Please try https://github.com/cmbant/getdist/commit/b44620770e81274c71bfc57ecf7871ace3ab8649?
