### ISSUE TITLE
plot log(liklihood) in 3rd axis using 3D scatter plot

### ISSUE THREAD

**Issue by github-arpita** [cmbant/getdist#110]
I  want to plot the chi-square or log(likelihood) in the third axis along with contour plots of two parameters using a scatter plot. Also, I want to know the chi-square value corresponding to every point within 2sigma contours. How can I do that?

**Comment by cmbant** [comment]
Please ask questions on CosmoCoffee, this is for bugs.
You can plot chi2_ variables like any other parameter, but there are no specific functions for those things.
