### ISSUE TITLE
Update conda-forge package 

### ISSUE THREAD

**Issue by davecwright3** [cmbant/getdist#111]
v1.4.6 changes the return type of `1DDensity.Prob`. I maintain a package that depends on `getdist` and uses this function. We set our version constraints `getdist` >=1.4.6 <2.0.0 and updated our code to handle the changed return types. 

This currently only works for PyPI because the conda-forge package hasn't been updated. Merging https://github.com/conda-forge/getdist-feedstock/pull/7 would solve this issue.

**Comment by cmbant** [comment]
I'm not sure why there is a conda-forge feedstock, it's not something I have made and does not seem necessary given getdist is pure python. I do not have write access to the feedstock so cannot merge anything.

**Comment by davecwright3** [comment]
My apologies, I assumed you were the maintainer, but I should have checked. I will get in contact with the maintainers of the conda-forge package.
