### ISSUE TITLE
Rotate colour bar

### ISSUE THREAD

**Issue by inigozubeldia** [cmbant/getdist#112]
Hello,

I've made this triangle plot with triangle_plot and would like to rotate the colour bar so that it doesn't overlap with the legend. Do you know how could I do this? Thanks!
[results_so_mcmc_onlycosmo_cosmo.pdf](https://github.com/cmbant/getdist/files/14054493/results_so_mcmc_onlycosmo_cosmo.pdf)

**Comment by cmbant** [comment]
Nothing built in. To add an option, you'd need to edit below line 2563 of plots.py

**Comment by cmbant** [comment]
Did you get this working? Happy to merge PR if you want to add a parameter to support this.

**Comment by inigozubeldia** [comment]
I haven't managed to fixed it - instead, we're placing the legend over the plot, instead of within it (the most I managed to is to rotate the colours within the colour bar).

Thanks!
