### ISSUE TITLE
Issues with units of axes scaling and scaling means

### ISSUE THREAD

**Issue by alishaexe** [cmbant/getdist#114]
I'm having some issues with getdist scaling the values of my means and the values on the axes. When I say scaling I do mean numerically and not fontsizes.

So in the two pictures; for the _A file, my mean values for Omega_* and nt are 10^-10, 2/3 respectively. But when they're being plotted it scales them both up by a magnitude of 10^3 so that Omega_* is ~10^-7 and nt ~10^3. I'd like them to remain their true values because I need to be able to compare them; and it scales differently for each one.
So for _B, where the means are 10^-9 and 0.01 it scales the mean values by the factor of 10^1, but then the axes scale differently compared to how they were for _A. which makes it impossible to compare the errors on the two scenarios.

Is there a way I can stop the scaling of the values? (I've included my plotting code in case that's helpful :) )

![FISHERLISA_A](https://github.com/cmbant/getdist/assets/119526666/26c6146c-b267-468a-b14d-e460aaa4a760)
![FISHERLISA_B](https://github.com/cmbant/getdist/assets/119526666/1dd65965-ecfe-46c0-990f-0a4b9db0423c)

```python
covmA = np.linalg.inv((FMLA))
covmB = np.linalg.inv((FMLB))


meansA = np.array((10**(-10),2/3))
meansB = np.array((10**(-9),0.01))
nsamp = int(1E6)
samps = np.random.multivariate_normal(meansA, covmA, size=nsamp)
samps2 = np.random.multivariate_normal(meansB, covmB, size=nsamp)
names = [r'\Omega_*',r'nt']
labels =  [r'\Omega_*',r'nt']
samples = MCSamples(samples=samps,names = names, labels = labels, label = 'Scenario A')
samples2 = MCSamples(samples=samps2,names = names, labels = labels, label='Scenario B')


g = plots.get_subplot_plotter(subplot_size=5)
g.settings.axes_fontsize=18
g.settings.legend_fontsize = 18
g.settings.axes_labelsize = 18
g.triangle_plot([samples], contour_colors = ['teal'],do_auto_scale=False,mean_labels='True',#param_limits=ranges,
                filled=True, markers={r'\Omega_*': meansA[0],'nt': meansA[1]}, title_limit=1)
plt.suptitle(r'Fisher Analysis for SNR of LISA Scenario A', fontsize = 18)

g = plots.get_subplot_plotter(subplot_size=5)
g.settings.axes_fontsize=18
g.settings.legend_fontsize = 18
g.settings.axes_labelsize = 18
g.triangle_plot([samples2], contour_colors = ['green'], mean_labels='True', do_auto_scale=False,
                filled=True, markers={r'\Omega_*': meansB[0],'nt': meansB[1]}, title_limit=1)
plt.suptitle(r'Fisher Analysis for SNR of LISA Scenario B', fontsize = 18)
```

**Comment by cmbant** [comment]
If you plot both on the same plot then you could compare them.. You can also specify fixed range using param_limits (dict for parameter names).

**Comment by alishaexe** [comment]
The param_limits sort of do the trick, thank you!
