### ISSUE TITLE
Rasterization option for large PDF

### ISSUE THREAD

**Issue by MartinKaercher** [cmbant/getdist#115]
Hi,
I am creating contour plots using `plots.getSubplotPlotter.triangle_plot()` for chains with around 13 parameters and I am overplotting 2-3 chains at the same time. This results in a fairly big PDF file (2.5Mb) (has to be PDF for the publication).
I was thinking if it would make sense to add an option in `triangle_plot` to enable rasterization in order to reduce the file size? Up to now I simply used the `**kwargs` to add a `rasterization` keyword argument to solve the problem.
Cheers,
Martin

**Comment by cmbant** [comment]
You've got lots of scatter samples? Contours are not usually very large (and don't usually want to rasterize for lack of scalability)

**Comment by MartinKaercher** [comment]
The chains contain around 8*10^4 samples but it shouldn't affect the file size of contours no?

**Comment by cmbant** [comment]
If you're not using scatter points, then yes number of samples doesn't directly matter much. Have you tried opening the PDF in acrobat and saving an optimized copy?  
I'm not sure we want rasterization as a standard option because of the loss of scalability.

**Comment by MartinKaercher** [comment]
Apparently optimizing PDF's in Acrobat is only possible in the pro version. In any case, I can use some other third party tool to do that. I do understand your point about the scalability with rasterized PDF's. In addition, this option would have to be introduced in fairly many places in the code if I have read it correctly.
