### ISSUE TITLE
GetDist-gui: boundary values of sample likelihood constraints stats

### ISSUE THREAD

**Issue by heredrzeam** [cmbant/getdist#119]
With getdist-gui, in the sample likelihood constraints panel, I got strange values of upper and lower bounds.

The lower bound value is bigger than best fit value, while the upper bound value is a abnormal small value.

Same problem came to me while I tested for other models. Standard LCDM model is used in this case.

Four chains are converged with |R-1|<0.01. The contour and marginalized constraints stats are quite normal. see red box below.

Bestfit values are also quite normal.

No idea why the boundary values of bestfit are strange. see yellow box below.

![1727151734078](https://github.com/user-attachments/assets/444f9244-2393-4ba6-ac50-6fb403d3ccd9)

The corresponding chains file is below:
[chains.zip](https://github.com/user-attachments/files/17142472/chains.zip)

**Comment by cmbant** [comment]
I can reproduce the best fit sample numbers, but I don't see the odd other numbers when I load it. Are you using the latest 1.5.2? (check Help, About)

**Comment by heredrzeam** [comment]
> I can reproduce the best fit sample numbers, but I don't see the odd other numbers when I load it. Are you using the latest 1.5.2? (check Help, About)

It turned out to be a version issue. After I upgraded from 1.4.3 to 1.5.2, the problem disappeared. Thanks a lot!!
