### ISSUE TITLE
Adding a curve to 2D contour plot

### ISSUE THREAD

**Issue by surgithub** [cmbant/getdist#12]
Hi Antony,

Getdist produces nice contour plots. I need to plot/add some curves in a 2D contour plot of two parameters. But I could not find any such option in the documentation of getdistplotter. I am able to plot my curves using the matplotlib.pyplot module. But I do not find a way to add these curves to the 2D contour plot given by getdistplotter. Please help.

**Comment by cmbant** [comment]
You can just use standard pyplot functions. There are similar questions on cosmocoffee (http://cosmocoffee.info/viewtopic.php?p=7365).

**Comment by surgithub** [comment]
Hi Antony, 

Thanks! It would be really useful if I am able to use the standard pyplot functions to modify the getdist plots.

I have read the cosmocoffee post, and seen the plot_gallery as well, as suggested by you. I am sorry that I am still not able to add my curves to the getdist 2D contour plot.

My curves are produced by the standard pyplot commands as given in the following:

import matplotlib.pyplot as plt
omegam =np.linspace(0.000001, 2.0,10000)
plt.ylim(-1,2)
plt.xlim(0,2)
omegav1 = 1-omegam
omegav2 = omegam/2
plt.plot(omegam, omegav1, 'g',linewidth =1.5)
plt.plot(omegam, omegav2, 'b',linewidth =1.5)
plt.grid(True)
plt.plot(omegam, omegav2, 'b',linewidth =1.5)
plt.show()

Now I want to add these curves in a 2D contour plot between two parameters (omegam and omega_Lambda) given by getdist. Hope you understand my problem now exactly.

Please do the needful.

Thanks.

**Comment by cmbant** [comment]
What exactly are you trying (combined with getdist that doesn't work?)

**Comment by surgithub** [comment]
Yes. I want to know how can I add the following two lines in the 2D contour plot of two parameters omegam and omega_Lambda produced by getdist:

omega_Lambda = 1-omegam
omega_Lambda = omegam/2

**Comment by cmbant** [comment]
I asked for exactly what you tried (full python), following the examples, that didn't work.

**Comment by surgithub** [comment]
OK. Following is the full python code that produces a 2D contour plot shown below:

`%matplotlib inline
import pylab as plb
import numpy as np
from __future__ import print_function
from getdist import plots, MCSamples
import matplotlib.pyplot as plt
import getdist, IPython
print('Version: ',getdist.__version__)
from __future__ import print_function
from getdist import plots, MCSamples
from getdist import loadMCSamples
import warnings
warnings.filterwarnings('ignore', '.*tight_layout.*',)
import numpy as np
samples1 = loadMCSamples('/home/sk/Desktop//CASE2_w0/chains_', dist_settings={'ignore_rows':0.3})
g = plots.getSinglePlotter(width_inch=6, ratio=3 / 5.)
g.settings.legend_fontsize = 12
g.plot_2d([samples1], 'Omega_m', 'Omega_Lambda', filled=True, 
    colors=['blue', 'green'])
plt.show()`

![image](https://cloud.githubusercontent.com/assets/18068751/26529408/0c006520-43dd-11e7-8012-e071dab95df6.png)

To the above getdist code/plot I want to add the following code/plot:

`omegam =np.linspace(0.000001, 2.0,10000)
plt.ylim((-1,2.0))
plt.xlim((0,2))
plt.plot(omegam, 1-omegam, 'g',linewidth =1.5)
plt.plot(omegam, omegam/2, 'b',linewidth =1.5)
plt.show()`

![image](https://cloud.githubusercontent.com/assets/18068751/26529507/afb09072-43de-11e7-849d-5ade30bad1dc.png)

**Comment by cmbant** [comment]
Just put your code before the first "show"? (though your axes probably won't make much sense)

**Comment by surgithub** [comment]
Thank you!!!
