### ISSUE TITLE
Effect of burnin fraction on Bayesian Mean chi^2

### ISSUE THREAD

**Issue by prakharbansal16** [cmbant/getdist#120]
I've generated MCMC chains for the w0wa CDM model and am comparing the w0wa contour to the LCDM case. I noticed that if I don't remove any burn-in, the contour plot shows very long tails, extending to the LCDM point (where w0 = -1 and wa = 0). However, after removing about 5% of the burn-in, the long tails disappear, and the contour becomes more accurate, with the region far from the LCDM point.

The issue I'm facing is with the Bayesian Mean Chi^2 (the Chi^2 value from the GetDist function ResultTable). I expected a similar change in Chi^2 values as with the contours after discarding burn-in. However, the Bayesian Mean Chi^2 only changes slightly when removing a fraction of the burn-in. Specifically, the delta Chi^2 between LCDM and w0wa CDM is about 6.8 without removing the burn-in, and it becomes about 7.2 after discarding the burn-in.

This small change in Chi^2 seems counterintuitive, as the plot shows the w0wa contour to be at least 3-sigma away from the LCDM point. I'm unsure why the Bayesian Mean Chi^2 is not reflecting the clearer separation shown in the contour plot after burn-in removal.

**Comment by cmbant** [comment]
The burn in region usually has very low likelihood. Contours plots are much more sensitive to the number of samples in 5% tails.

This does not sound like a bug so closing (please ask questions on CosmoCoffee).
