### ISSUE TITLE
triangle_plot failure

### ISSUE THREAD

**Issue by s-ilic** [cmbant/getdist#13]
Hello all,
I've had a few strange troubles with the triangle_plot routine, on completely different machines (my own laptop and a computing cluster) and with completely different chains : (apparently) at random, it fails horribly to produce one or several of the 2D contours in the triangle plot.

See e.g. here (6th row, 5th column) :
[plot.pdf](https://github.com/cmbant/getdist/files/1036070/plot.pdf)

Here (6th row, 3rd column) :
[LDMD.pdf](https://github.com/cmbant/getdist/files/1036078/LDMD.pdf)

Or this one, which pretty much uses the same chains but fails for a different plot (5th row, 3rd column)
[LDMD (copy).pdf](https://github.com/cmbant/getdist/files/1036079/LDMD.copy.pdf)

Any idea what could be the cause of it ?

Thanks in advance !

Cheers,
Stéphane

**Comment by cmbant** [comment]
Not sure. Could you share on Dropbox or similar a zip of the offending chain files and getdist script to reproduce the issue?

**Comment by cmbant** [comment]
Btw, it's unlikely to be a good idea having a parameter of amplitude 1e-27 (i.e. rescale \lambda_{DM} to units of 1e-27?)

**Comment by s-ilic** [comment]
The weird thing is that any of these "offending" chains can give perfectly good 2D contours when plotted alone, or in another order, etc... I'll try to make a zip so that you could reproduce the issue !

**Comment by s-ilic** [comment]
Mmmm... while I was trying to create a scenario where you consistently get the bug I mentioned, I discovered something : the bug seems to be linked to the various "import" I do at the beginning of my python script... Some examples :
_ if I do an "import matplotlib.pyplot as plt" (I don't use "plt" in this particular script) before my "from getdist import plots", I get the bug in one of the 2D contour
_ if I do an "from getdist import plots,MCSamples,loadMCSamples" (but I don't use the MCSamples loadMCSamples function) I also get a bug, but in another 2D contour of the triangle...

Does it ring any bell to you ? Should I still send you a zip with files that produces one of the situation I mention here ?

Thanks in advance,
S.

**Comment by cmbant** [comment]
Weird, pleases do.

**Comment by s-ilic** [comment]
Here you go :
https://drive.google.com/open?id=0B0uAGvghh-PObnhIQVVpQnJqUUk

The archive contains a 4 MCMC chains, 5 python scripts and a bunch of .pdf that corresponds to my outputs for these scripts. In each script, I put some comments on what's wrong with the ouputs on my machine.

Some info on my machine :
Linux Mint 17.3
Python 2.7.6
matplotlib.__version__ = 2.0.0
getdist.__version__ = 0.2.7
scipy.__version__ = 0.19.0
numpy.__version__ = 1.12.1

Thanks !
S.

**Comment by cmbant** [comment]
Thanks. The bounds issue in a should now be fixed on the devel branch. 

Generally the issues seem to be unstable, e.g. putting in a print statement to see them, or running with debugging, can make them go away. So maybe to do with floating point rounding/uninitialized variable/etc, which is hard to track down. It may be to do with boundary correction, do you still see issues if you set boundary_correction_order=0? e.g.

`plots.getPlotter(chain_dir=r'./', analysis_settings={'boundary_correction_order':0})`

**Comment by s-ilic** [comment]
Using the "boundary_correction_order=0" setting makes all the previously mentioned issues disappear (except the bound issue, but I did not update getdist to the devel branch).

Does this help pinpointing the issue ? Is there any significant impact on the plotted results when using this particular setting ?

**Comment by cmbant** [comment]
I found and fixed a likely bug in how the convolutions were being cached. That could have given this erratic behaviour. Could you try the devel branch now? (with default boundary correction)

**Comment by s-ilic** [comment]
Seems like all the problems have disappeared (including the bound issue), thanks a lot ! I guess we can close the issue ?

**Comment by cmbant** [comment]
Great, thanks. Now merged with master branch.
