### ISSUE TITLE
Oddity when trying to name parameters in chains

### ISSUE THREAD

**Issue by jbrinchmann** [cmbant/getdist#15]
Hi,
I was trying to use getdist with some chains created by pymultinest. It all works well, but I was trying to add names to the parameters without creating a .paramnames file (which does work btw). I thought I then could do:

samples = loadMCSamples('/data2/jarle/PIModels/Testing/MCMC/SDSSTest/CL01sdss-000002.txt')
nm = samples.getParamNames()
nm.setLabels(('LOGZ', 'CO', 'XSI', 'LOGU', 'TAUV'))
nm.setWithNames(('LOGZ', 'CO', 'XSI', 'LOGU', 'TAUV'))
samples.setParamNames(nm)

That works without making any noise, but when I run a corner plot I get an 
AttributeError: 'ParamInfo' object has no attribute 'limmin' (see below for the full trace). I had a brief look at the code but I did not immediately see what was going on - clearly this was a bad idea, but is there are a better way to do this without making the .paramnames file? 

      Thanks,
                    Jarle

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-117-9fe30ea25bc7> in <module>()
----> 1 g.triangle_plot(samples_G16, filled=True)

/Users/jarle/anaconda/lib/python2.7/site-packages/getdist/plots.pyc in triangle_plot(self, roots, params, legend_labels, plot_3d_with_param, filled, shaded, contour_args, contour_colors, contour_ls, contour_lws, line_args, label_order, legend_ncol, legend_loc, upper_roots, upper_kwargs, **kwargs)
   1949             self.plot_1d(roots1d, param, do_xlabel=i == plot_col - 1,
   1950                          no_label_no_numbers=self.settings.no_triangle_axis_labels,
-> 1951                          label_right=True, no_zero=True, no_ylabel=True, no_ytick=True, line_args=line_args)
   1952             # set no_ylabel=True for now, can't see how to not screw up spacing with right-sided y label
   1953             if self.settings.no_triangle_axis_labels:

/Users/jarle/anaconda/lib/python2.7/site-packages/getdist/plots.pyc in plot_1d(self, roots, param, marker, marker_color, label_right, no_ylabel, no_ytick, no_zero, normalized, param_renames, **kwargs)
   1394         if marker is not None: self.add_x_marker(marker, marker_color)
   1395         if not 'lims' in kwargs:
-> 1396             xmin, xmax = self._check_param_ranges(plotroot, plotparam.name, xmin, xmax)
   1397             if normalized:
   1398                 mx = plt.gca().yaxis.get_view_interval()[-1]

/Users/jarle/anaconda/lib/python2.7/site-packages/getdist/plots.pyc in _check_param_ranges(self, root, name, xmin, xmax)
    801         """
    802         d = self.paramBoundsForRoot(root)
--> 803         low = d.getLower(name)
    804         if low is not None: xmin = max(xmin, low)
    805         up = d.getUpper(name)

/Users/jarle/anaconda/lib/python2.7/site-packages/getdist/mcsamples.pyc in getLower(self, name)
   2005         par = self.paramNames.parWithName(name)
   2006         if par:
-> 2007             return par.limmin
   2008         return None
   2009 

AttributeError: 'ParamInfo' object has no attribute 'limmin'

**Comment by cmbant** [comment]
Does calling "updateBaseStatistics" help? Certainly using a .paramnames file is usually easiest if loading from a file.

**Comment by jbrinchmann** [comment]
Aha! Yes, calling updateBaseStatistics did fix that problem. I did not think to try that since I was only modifying labels I thought :)

Yes, indeed creating .paramnames files is probably the way to go but I had a large bunch of chains and wanted to avoid that particular step if possible. When I create them next I'll probably output .paramnames files as a matter of course.

Thanks for the help & for the very nice package that getdist is!
