### ISSUE TITLE
68% CL

### ISSUE THREAD

**Issue by SimoneAmmazzalorso** [cmbant/getdist#19]
Hi,

thank you for your package, it is working perfectly!
I was wondering if there is the possibility of plotting only the 68% line in the triangle plot. Default are 68% and 95% (I think). I haven't found this answer in the documentation.

**Comment by cmbant** [comment]
You need to change num_plot_contours in the settings (GetDistPlotSettings instance). e.g. in GetDist Gui under plot settings on the options menu.

**Comment by SimoneAmmazzalorso** [comment]
Thank you! I missed that setting, now it works!
