### ISSUE TITLE
Font sizes do not appear to be working

### ISSUE THREAD

**Issue by matthewkirby** [cmbant/getdist#25]
I was recently looking for an alternative to making triangle/corner plots that smooth and plot quickly when chains are large and was led here. The examples and documentation clearly describe how to make all sorts of plots but something that I found lacking was examples and clear documentation for configuring the plots. For example, I really like the ability to create an object with plotting settings that can then be passed around. This will let me save a file of config info that I can just load whenever I want to make a nice looking plot. However, I have found that not all of the settings work. See the following example:

Begin with a single 1d plot
```python
# Setup
rdata = np.random.normal(0., 1., 10000)
samples = MCSamples(samples=rdata, names=['x'], labels=['x'], ranges={'x':(-5,5)})

# Settings object
settings = plots.GetDistPlotSettings()

# Plot
single = plots.getSubplotPlotter(width_inch=4, settings=settings)
single.plot_1d(samples, param='x', filled=True, normalized=True)
```
<img width="296" alt="screen shot 2018-10-16 at 11 15 31 am" src="https://user-images.githubusercontent.com/5395125/47037828-d6613700-d134-11e8-95e9-87f84211ea97.png">

Now I want to remove the p from the left side.
```python
# Setup
rdata = np.random.normal(0., 1., 10000)
samples = MCSamples(samples=rdata, names=['x'], labels=['x'], ranges={'x':(-5,5)})

# Settings object
settings = plots.GetDistPlotSettings()
settings.norm_prob_label = False

# Plot
single = plots.getSubplotPlotter(width_inch=4, settings=settings)
single.plot_1d(samples, param='x', filled=True, normalized=True)
```
<img width="262" alt="screen shot 2018-10-16 at 11 17 08 am" src="https://user-images.githubusercontent.com/5395125/47037918-09a3c600-d135-11e8-89c1-7361ac40bbd0.png">

It works! Now I want to increase the fontsize of the axes ticks and labels the same way but it does not work.
```python
# Setup
rdata = np.random.normal(0., 1., 10000)
samples = MCSamples(samples=rdata, names=['x'], labels=['x'], ranges={'x':(-5,5)})

# Settings object
settings = plots.GetDistPlotSettings()
settings.norm_prob_label = False
settings.axes_fontsize = 20
settings.lab_fontsize = 20

# Plot
single = plots.getSubplotPlotter(width_inch=4, settings=settings)
single.plot_1d(samples, param='x', filled=True, normalized=True)
```
<img width="254" alt="screen shot 2018-10-16 at 11 19 58 am" src="https://user-images.githubusercontent.com/5395125/47038072-6ef7b700-d135-11e8-882e-119d06a3bcf0.png">

But when I directly set the properties in the settings object that is a member of the plotter class it does.
```python
# Setup
rdata = np.random.normal(0., 1., 10000)
samples = MCSamples(samples=rdata, names=['x'], labels=['x'], ranges={'x':(-5,5)})

# Settings object
settings = plots.GetDistPlotSettings()
settings.norm_prob_label = False
settings.axes_fontsize = 20
settings.lab_fontsize = 20

# Plot
single = plots.getSubplotPlotter(width_inch=4, settings=settings)
single.settings.axes_fontsize = 20
single.settings.lab_fontsize = 20
single.plot_1d(samples, param='x', filled=True, normalized=True)
```
<img width="246" alt="screen shot 2018-10-16 at 11 21 22 am" src="https://user-images.githubusercontent.com/5395125/47038157-a23a4600-d135-11e8-9802-767214323608.png">

**Comment by matthewkirby** [comment]
I think this code snippet show the issue more clearly.
```python
settings = plots.GetDistPlotSettings()
settings.norm_prob_label = False
settings.axes_fontsize = 15

print("Before: {} {}".format(settings.axes_fontsize, settings.norm_prob_label))
single = plots.getSubplotPlotter(width_inch=4, settings=settings)
print("After: {} {}".format(settings.axes_fontsize, settings.norm_prob_label))
```
```
Before: 15 False
After: 8 False
```

**Comment by cmbant** [comment]
The getSubplotPlotter is designed to set sizes appropriately for subplots, and hence will change settings relating to size. For single plots you probably want getSinglePlotter. As you note, the thing to do to tweak settings is to change them afterwards.

**Comment by matthewkirby** [comment]
Good call, after playing around with it a bunch more the default sizes are great!

Thanks for the pointer on getSinglePlotter as well, I had missed that.

I am going to close the issue.
