### ISSUE TITLE
Bad behaviour of mcsamples.MCSamples ?

### ISSUE THREAD

**Issue by s-ilic** [cmbant/getdist#26]
Hi,

A. Ferté (@aferte) brought to my attention a problem with the 0.3.0 version of getdist : essentially, if one tries to create an MCSamples instance by providing an (numpy) array for the samples and some weights, a ValueError is raised as soon as one of the weights is significantly smaller that the rest ("ValueError: chains are separated, makeSingle first or call filter on individual chains").

A minimal example to illustrate the issue :
```
import numpy as np
from getdist.mcsamples import MCSamples

samps = np.random.rand(10000, 3)
weights = np.ones(10000)
weights[0] = 0 # one tiny weight

MC = MCSamples(samples=samps,weights=weights) # raises an error
```

It seems that the presence of at least one "very small" weight triggers the use of the "filter" function in order to get rid of the samples with (relatively) negligible weights. However, the "filter" function as defined in the "Chains" class starts by checking if "self.chains" is set to "None" -- which it is not at that point in the execution, but rather set to an empty list "[ ]", hence the error raised. I assume this is not an intended behaviour ?

Thanks in advance !

**Comment by cmbant** [comment]
Thanks, try 7dae938d52875d38f063862be1c2e5285f8dec3a

**Comment by s-ilic** [comment]
Now it works, thanks a ton !
