### ISSUE TITLE
Disable burn in for nested sampling chains

### ISSUE THREAD

**Issue by williamjameshandley** [cmbant/getdist#27]
Burn in has no meaning for nested sampling. Ideally it should be disabled or throw an exception if users try to use it in the case of analysing nested sampling chains. This was the root cause of this issue:

https://github.com/PolyChord/PolyChordLite/issues/6#issuecomment-446764417

@JesusTorrado has suggested that something like this [may be possible](https://github.com/PolyChord/PolyChordLite/issues/6#issuecomment-446877996).

**Comment by cmbant** [comment]
If you make a chain_root.properties.ini file with "burn_removed=True", that should ensure nothing is removed (the default is also no burn removed). 

We could add something with a more intuitive name that has the same effect, e.g. "sampling_method=nested".

(if you just want posteriors, probably usually the start of nested sampling chains can actually be removed since the samples have no weight there)

**Comment by williamjameshandley** [comment]
> If you make a chain_root.properties.ini file with "burn_removed=True", that should ensure nothing is removed (the default is also no burn removed).

I guess this would be a modification to polychord's outputs, which I'll happily put in if we agree that this is the cleanest way to do it. @JesusTorrado -- what did you originally have in mind? Feel free to make a github issue on the [PolyChord](https://github.com/PolyChord/PolyChordLite/issues/new) repo if necessary.

> (if you just want posteriors, probably usually the start of nested sampling chains can actually be removed since the samples have no weight there)

I agree that in most cases this is definitely true, but if there is not that much prior to posterior compression, then this can cause issues that are [confusing for users](https://github.com/PolyChord/PolyChordLite/issues/6)

**Comment by vivianmiranda** [comment]
Hi

Yes the default is no burning but usually what we do is to cp py files from older projects and redo-it - because it contains all the mathplotlib tweaks - so it is very easy to get legacy burn-in by mistake

**Comment by JesusTorrado** [comment]
If the samples have been generated with Cobaya, this option (either `sampling_method=nested` or `burn_removed=True`) can be set at loading without needing to create a properties.ini, since we know the sampler from the input file. That's more or less what I was thinking about.

**Comment by williamjameshandley** [comment]
@JesusTorrado that  sounds ideal. I've created an [issue on Cobaya](https://github.com/CobayaSampler/cobaya/issues/17#issue-391022643) so that we don't forget about this

**Comment by cmbant** [comment]
Another thing I'm not sure getdist handles appropriately for nested samples is the estimate of the effective sample number used for KDE, eq. 31 of

http://cosmologist.info/notes/GetDist.pdf

**Comment by williamjameshandley** [comment]
@cmbant . I agree that such a formula won't be correct for NS. This may explain some of the behaviour I've seen in the past where I've had to manually adjust the smoothing factor. In general, it would be safer to assume that samples from MultiNest or PolyChord are effectively independent.

**Comment by williamjameshandley** [comment]
@JesusTorrado, am I correct in assuming that you're proposing this as a quick-fix so that we can use GetDist as-is, and let it estimate effectively zero correlation (I agree that the fact that they're likelihood ordered going in is going to result in odd behaviour if part of the algorithm tries to estimate correlation).

**Comment by JesusTorrado** [comment]
Yes, but I have not read Antony's note, so I am not completely sure whether that's safe enough.

**Comment by JesusTorrado** [comment]
> so that we can use GetDist as-is

@williamjameshandley I think I misunderstood you: I was proposing to do the change in GetDist, at load time, instead of in Cobaya.
