### ISSUE TITLE
Segfault with newest versions of matplotlib and pyside

### ISSUE THREAD

**Issue by williamjameshandley** [cmbant/getdist#29]
I'm currently getting a segfault on my system when running `GetDistGUI.py`. It seems to be an issue with the latest versions of Qt, and it is fixed on my system by reordering the imports in `getdist.gui.mainwindow.py` so that the `getdist.gui.SyntaxHighlight` import line is after the initial `getdist` imports.

I can submit a PR with this 'fix', providing that it doesn't disrupt anybody else's system

**Comment by cmbant** [comment]
Changing the order seems OK on my system with PySide on Windows (I see no problem with either). There are quite a lot of possible system configs, so possibly depends on whether using PySide or PySide2, which matplotlib version and system?

**Comment by williamjameshandley** [comment]
Indeed, I'm not entirely sure it's useful to try and work out which interaction between these shifting modules is causing this. I think conceptually it makes more sense to import the gui parts after the main parts of getdist. Submitted as PR #30
