### ISSUE TITLE
LWS for 2D plot not working?

### ISSUE THREAD

**Issue by vivianmiranda** [cmbant/getdist#38]
I have been having difficulty in adjusting the width of lines in 2D contours in triangle plots. Let me give an example

[plot17.pdf](https://github.com/cmbant/getdist/files/3848244/plot17.pdf)

Here is the code.

`g.triangle_plot(roots, params, plot_3d_with_param=param_3d, 
filled=False, shaded=False,
line_args=[
{'lw': 1.4, 'ls': 'solid', 'color':'red'},
{'lw': 0.8, 'ls': 'dashed', 'color':'black'}
],
legend_loc=(0.5,0.8),
contour_colors=['red','black'],
contour_ls=['solid','dashed'],
contour_lws=[1.4,0.8],
legend_labels=[
'DES Planck $\\theta_\\star$, NS',
'DES Flat Prior'
]
)`

Any clues?

**Comment by cmbant** [comment]
Looks OK for me. Are you using getdist 1? (the axis tick labels also look bad, which *shouldn't* happen in version 1.0+)

**Comment by cmbant** [comment]
Can we close this or still an issue?
