### ISSUE TITLE
getSubplotPlotter function is wrong in tutorial

### ISSUE THREAD

**Issue by lbarosi** [cmbant/getdist#39]
This is really just a typo in https://getdist.readthedocs.io/en/latest/plot_gallery.html. 

````
# Triangle plot
g = plots.get_subplot_plotter()
g.triangle_plot([samples, samples2], filled=True)
````

should be 
````
# Triangle plot
g = plots.getSubplotPlotter()
g.triangle_plot([samples, samples2], filled=True)
````

**Comment by cmbant** [comment]
Are you using getdist 1.0+? getSubplotPlotter it deprecated now.

**Comment by lbarosi** [comment]
Sorry, I was running in the wrong environment (getdist was in 0.3).
Thanks.
