### ISSUE TITLE
GetDist cannot load files with only one line

### ISSUE THREAD

**Issue by potassium-chloride** [cmbant/getdist#40]
GetDist fails if chain directory contains a file with only one line. Bad place is in the file getdist/chains.py in the class "WeightedSamples" in constructor at line 178:
`cols = loadNumpyTxt(filename, skiprows=ignore_rows)`
In this line NumPy returns a 2-dimensional array if the file contains 2 or more lines or NumPy returns a 1-dimensional array if the file contains only 1 line. It causes crash in other GetDist parts.

`Traceback (most recent call last):`
`  File "Plotter_start.py", line 10, in <module>`
`    chaindata = loadMCSamples(chainsname,dist_settings={'ignore_rows': 0.0,'smooth_scale_2D':-1})`
`  File "/usr/local/lib/python2.7/dist-packages/GetDist-0.3.3-py2.7.egg/getdist/mcsamples.py", line 93, in loadMCSamples`
`    samples.readChains(files)`
`  File "/usr/local/lib/python2.7/dist-packages/GetDist-0.3.3-py2.7.egg/getdist/mcsamples.py", line 477, in readChains`
`    self.loadChains(self.root, files_or_samples, weights=weights, loglikes=loglikes)`
`  File "/usr/local/lib/python2.7/dist-packages/GetDist-0.3.3-py2.7.egg/getdist/chains.py", line 1060, in loadChains`
`    self.chains.append(WeightedSamples(fname, **WSkwargs))`
`  File "/usr/local/lib/python2.7/dist-packages/GetDist-0.3.3-py2.7.egg/getdist/chains.py", line 181, in __init__`
`    self.setColData(cols, are_chains=files_are_chains)`
`  File "/usr/local/lib/python2.7/dist-packages/GetDist-0.3.3-py2.7.egg/getdist/chains.py", line 201, in setColData`
`    self.setSamples(coldata[:, 2:], coldata[:, 0], coldata[:, 1])`
`IndexError: too many indices for array`

This situation can occur if user started MontePython script but interrupted it very fast.

**Comment by cmbant** [comment]
Thanks, should be fixed with https://github.com/cmbant/getdist/commit/b15c7185ab8f7645d7528b17630ab9e58fde4127.

You might want to install pandas - will make reading chain files faster.
