### ISSUE TITLE
param_limits in getdist.plots.triangle_plot(...) has no effect on the Y axis

### ISSUE THREAD

**Issue by potassium-chloride** [cmbant/getdist#41]
I tries to fix limits in triangle plot by param_limits={'paramname':(minval,maxval)}. It works on the X axis exactly but no effect for the Y axis.

I hot fixed it in my plot script by call
`for ay in range(params.index('paramname')):
    TrianglePlotObject.subplots[params.index('paramname'),ay].set_ylim((minval, maxval))`
after triangle_plot(...) but it is bad solution, I think.

I found another solution: replacing line 2447 in getdist/plots.py from `                if i == 0:` to `                if i != i2:`

P.S.:
Calling `TrianglePlotObject.subplots[params.index('paramname'),0].set_ylim((minval, maxval))` works too. I have no idea why `                if i == 0:ax.set_ylim(lims[i2])` doesn't work in GetDist

**Comment by cmbant** [comment]
Do you have a test case to reproduce the issue? (and which matplotlib version?)

**Comment by potassium-chloride** [comment]
I use
matplotlib.__version__ == '3.1.3'
with Python 3.7.6 (Anaconda)

Right now I don't have the ability to attach Monte Carlo chains. Screenshots attached:
What I see:
![whatIsee](https://user-images.githubusercontent.com/34630909/79112183-ad9c1b00-7d86-11ea-9d8d-a4baf7ea0dce.png)
What I want:
![whatIwant](https://user-images.githubusercontent.com/34630909/79112185-ae34b180-7d86-11ea-8929-4167f0c98103.png)

Python code:
```
import getdist.plots as plots
from getdist import loadMCSamples
...
chaindata = loadMCSamples(chainsname,settings={'ignore_rows': 0.0,'smooth_scale_2D':-1})
chaindata2 = loadMCSamples(chainsname2,settings={'ignore_rows': 0.0,'smooth_scale_2D':-1})

g = plots.getSubplotPlotter()
g.settings.solid_contour_palefactor = 0.8
g.settings.legend_fontsize=10
g.settings.num_plot_contours = 2

p = chaindata.getParams() 
chaindata.addDerived(1e3*p.p1, name='newparamname', label='newparamname')
'''newparamname doesn't exist in chaindata but I want to see diagrams for newparamname in chaindata2. It needs only for disable errors in plot script and 1e3*p.p1>>newparamname.'''

g.triangle_plot(
	[chaindata,chaindata2],
	['p1','p2','p3','p4','p5','p6','newparamname','p7','p8','p9','h'],
	filled=[True,True],
	colors=['red','blue'],
	alphas=[1,0.75],
	ls=['-','-','-'],
	legend_labels=['$chain data 1$','$chain data 2$','$old chains...$'],
	line_args=[{'lw':1.2,'ls':'-', 'color':'red'},{'lw':1.2,'ls':'-', 'color':'blue'},{'lw':1.2,'ls':'-', 'color':'black'}],
	param_limits={'newparamname':(-3, 12)}
)
for ax in range(0,11): # p1
	g.subplots[ax,0].axvline(1., color='gray', ls='--',lw=1)

for ax in range(1,11): # p2
	g.subplots[ax,1].axvline(2., color='gray', ls='--',lw=1)

for ax in range(2,11): # p3
	g.subplots[ax,2].axvline(-1., color='gray', ls='--',lw=1)

for ax in range(3,11): # p4
	g.subplots[ax,3].axvline(-0.2, color='gray', ls='--',lw=1)

for ax in range(10,11): # h
	g.subplots[ax,10].axvline(0.677, color='gray', ls='--',lw=1)

g.export("chaindata12_triangle.pdf")
```
Probably, matplotlib clears the limits  after adding a new subplot. For the X axis, GetDist first creates graphs and then sets limits (top to bottom), so the X axis doesn't have this problem.

**Comment by cmbant** [comment]
Can you not use the other order
`
[chaindata2,chaindata]
`
without adding the fake new parameter (probably with the wrong limits)?

**Comment by potassium-chloride** [comment]
I removed all `chaindata` from my code and set `param_limits={'newparamname':(-30, 120)}`. It is not good for human representation but good for bug illustration:
![onechainillustration](https://user-images.githubusercontent.com/34630909/79114437-f60a0780-7d8b-11ea-9fbe-c0f021e116b6.png)

In right part we see working limits from -30 to 120. In top part we see `newparamname` with automatic matplotlib limits.
Code:
```
import getdist.plots as plots, os
from getdist import loadMCSamples

#chainsname='..../2020-04-11_999999_'
#chaindata = loadMCSamples(chainsname,settings={'ignore_rows': 0.0,'smooth_scale_2D':-1})
chainsname2="...../2020-04-11_999999_"
chaindata2 = loadMCSamples(chainsname2,settings={'ignore_rows': 0.0,'smooth_scale_2D':-1})

g = plots.getSubplotPlotter()
g.settings.solid_contour_palefactor = 0.8
g.settings.legend_fontsize=10
g.settings.num_plot_contours = 2

#p = chaindata.getParams() 
#chaindata.addDerived(1e3*p.p_1, name='newparamname', label='newparamname')


g.triangle_plot(
	[chaindata2],
	['p1','p2','p3','p4','p4','p5','newparamname','p6','p7','p8','h'],
	filled=[True,True],
	colors=['red','blue'],
	alphas=[1,0.75],
	ls=['-','-','-'],
	legend_labels=['$chain data 1$','$chain data 2$','$old chains...$'],
	line_args=[{'lw':1.2,'ls':'-', 'color':'red'},{'lw':1.2,'ls':'-', 'color':'blue'},{'lw':1.2,'ls':'-', 'color':'black'}],
	param_limits={'newparamname':(-30, 120)}
	)

g.export("test_triangle.pdf")```

**Comment by cmbant** [comment]
OK thanks, I see
