### ISSUE TITLE
TypeError from get_single_plotter()

### ISSUE THREAD

**Issue by WHKinney** [cmbant/getdist#46]
Hi --

I was having issues with receiving a TypeError when calling plots.get_single_plotter() in GetDist 1.1.1 with Matplotlib 2.1.1. See screenshot. 

![Screenshot from 2020-05-18 09-56-45](https://user-images.githubusercontent.com/44494471/82221549-26464800-98ee-11ea-98ee-67ede4b79253.png)

The problem seems to be with the constrained_layout option in make_figure(). I fixed by changing the code after line 1708 as follows:

Old code:

         if self.settings.constrained_layout:
            self.fig = plt.figure(figsize=figsize, constrained_layout=True)
        else:
            self.fig = plt.figure(figsize=figsize)
        self.gridspec = matplotlib.gridspec.GridSpec(nrows=self.plot_row, ncols=self.plot_col, figure=self.fig)

New code:

        if self.settings.constrained_layout:
            self.fig = plt.figure(figsize=figsize, constrained_layout=True)
            self.gridspec = matplotlib.gridspec.GridSpec(nrows=self.plot_row, ncols=self.plot_col, figure=self.fig)
        else:
            self.fig = plt.figure(figsize=figsize)
            self.gridspec = matplotlib.gridspec.GridSpec(nrows=self.plot_row, ncols=self.plot_col)

Not sure if this is an optimal fix, but seems to work fine for me.

**Comment by cmbant** [comment]
The install_requires has matplotlib >= 2.2.0, if you do pip install does it not account for that?

**Comment by WHKinney** [comment]
Yup, upgrading to 3.2.1 fixed the issue. Thanks.
