### ISSUE TITLE
Is it possible to thread triangle plots

### ISSUE THREAD

**Issue by vivianmiranda** [cmbant/getdist#47]
Hi Prof Lewis, 

Is it possible to thread big triangle plots - plots with more than 10x10 dims? I am trying triangle plots with 30 dims and GetDist is really slow, even with thin chains. I would never include such a plot in a paper, but these large triangle plots are great for visual inspection of the chain. 

Best and stay safe
Vivian Miranda

**Comment by cmbant** [comment]
It should already internally be using openmp for the FFTs etc, do you not see reasonably high CPU usage? Also make sure you have the latest getdist updates. I can do 10x10 for one chain in a few seconds on my laptop for Planck chains (though obviously slower for non-fast-dragging sampling methods that produce much larger chains, and will be slower if you have lots of parameters with very tight degeneracies).

**Comment by cmbant** [comment]
PS. Please can you answer or close https://github.com/cmbant/getdist/issues/38?

**Comment by vivianmiranda** [comment]
Thanks - w/ latest GetDist I get 140% ish CPU usage. Some speed-up but the plot still takes a long time to be constructed - and I have intel extreme cores.

**Comment by cmbant** [comment]
What chains are they/how big?

**Comment by vivianmiranda** [comment]
Even with total chain size < 10 megabytes - scripts like the one below take a really long time

[10.txt](https://github.com/cmbant/getdist/files/4726232/10.txt)

**Comment by cmbant** [comment]
It will take five times longer if plotting 5 chains at once. Why did you change all the default settings? Increasing fine_bins_2D and num_bins_2D will certainly use more memory and slow it down. I'm surprising you need to change that if you are just making "quick-look" plots for inspection.

**Comment by cmbant** [comment]
You can use code like this to see where it is spending the time
```
    import pstats
    from cProfile import Profile
    from io import StringIO

    rof = Profile()
    prof.enable()
    <--- code to test here ---->
    prof.disable()
    s = StringIO()
    ps = pstats.Stats(prof, stream=s)
    ps.strip_dirs()
    ps.sort_stats('time')
    ps.print_stats(10)
    ps.sort_stats('cumtime')
    ps.print_stats(10)
    print(s.getvalue())
```

**Comment by vivianmiranda** [comment]
Hi Lewis,

I dont need to change that - it is the kind of settings that I just copy paste a million times from past examples

What is a good value for quick look plots?

Vivian Miranda

On Jun 4, 2020, at 12:57 AM, Antony Lewis <notifications@github.com> wrote:

﻿

External Email

You can use code like this to see where it is spending the time

    import pstats
    from cProfile import Profile
    from io import StringIO

    rof = Profile()
    prof.enable()
    <--- code to test here ---->
    prof.disable()
    s = StringIO()
    ps = pstats.Stats(prof, stream=s)
    ps.strip_dirs()
    ps.sort_stats('time')
    ps.print_stats(10)
    ps.sort_stats('cumtime')
    ps.print_stats(10)
    print(s.getvalue())

**Comment by cmbant** [comment]
Just use defaults for anything you don't need to change (delete all your analysis settings dictionary entries that you don't want to override)

**Comment by vivianmiranda** [comment]
Thank you

Vivian Miranda

On Jun 4, 2020, at 1:02 AM, Antony Lewis <notifications@github.com> wrote:

﻿

External Email

Just use defaults for anything you don't need to change (delete all your analysis settings dictionary entries that you don't want to override)
