### ISSUE TITLE
loadMCSamples not loading all chains if they have non-continuous numeration

### ISSUE THREAD

**Issue by carlosggarcia** [cmbant/getdist#48]
Hi,
I've noticed that `loadMCSamples` does not load all chains if the numbering is continuous. For instance, if you've got the following chains,
- 2019-11-29_350000__1.txt
- 2019-11-29_350000__3.txt
- 2019-11-29_350000__4.txt
`loadMCSamples` only loads `2019-11-29_350000__1.txt`. I found myself in this situation as one of my chains didn't converge and I renamed it to `2019-11-29_350000__2.txt-noconverged`, because I thought `loadMCSamples` would just would just skip that one. 

I've modified `chainFiles` in `chains.py` to allow for missing chains. It uses regular expressions. It can be seen in https://github.com/carlosggarcia/getdist/commit/7f4edc3f553fbfc2992aad6e07f18148a965bd6e. I have made some tests and it seems to work fine.

Carlos

**Comment by cmbant** [comment]
OK thanks, I added something similar in https://github.com/cmbant/getdist/commit/5abf2cb2ae960bd3a16f3acd01da49e16dc7f125
