### ISSUE TITLE
get1DDensityGridData not exporting to file

### ISSUE THREAD

**Issue by JFJesus** [cmbant/getdist#49]
Dear prof. Lewis,

I am having an issue with exporting likelihood data to a file, with get1DDensityGridData(parname,writeDataToFile=True) . I would like to export it in order to compare with other analyses and plot outside getdist. Before getdist version 1.1, I didn't have this issue. I have tried to downgrade to getdist 1.0, but pip has downgraded other packages too and it gave me another problems.

Any idea of how to do that in getdist 1.1.2?

Best regards.

**Comment by cmbant** [comment]
You can just access and save elements of the Density1D object that is returns as you like/needed.
https://getdist.readthedocs.io/en/latest/densities.html?highlight=density1d#getdist.densities.Density1D

**Comment by JFJesus** [comment]
It worked. Thank you!
