### ISSUE TITLE
triangle_plot does not center some of the parameters

### ISSUE THREAD

**Issue by taladi** [cmbant/getdist#53]
For some reason some of the plots in the triangle plot are not centered. Is there an option to rectify this?
I saw there is param_limits option (couldn't manage to understand how to use it correctly), anyway I need to center only some of the parameters (the others already appear in the center).

Thanks.

**Comment by cmbant** [comment]
See the argument option docs
https://getdist.readthedocs.io/en/latest/plots.html?highlight=triangle_plot#getdist.plots.GetDistPlotter.triangle_plot
