### ISSUE TITLE
Changing the axis  and tick labels in GetDist contour plots

### ISSUE THREAD

**Issue by borisbolliet** [cmbant/getdist#55]
Hi,

I have been trying to set custom axis label and ticks in contour plots.  

I was wondering whether this is possible in GetDist in a relatively easy way? 

Concretely, on the plot attached I would like to re-arrange the tick labels with 10^XX values, rather than the log10(XX) values, and change the axis labels accordingly, including the colorbar label and ticks.

Thanks a lot!
Boris

The corresponding script is:

    g = plots.getSubplotPlotter()
    g.settings.fig_width_inch = 5
    g.settings.axes_fontsize = 10
    g.settings.lab_fontsize =12
    g.settings.legend_fontsize = 15
    g.settings.alpha_filled_add=0.4
    g.settings.colorbar_label_pad = 5.
    g.settings.figure_legend_frame = False

    sample_list = []
    for s in range(len(all_samples)):
        sample_list.append(all_samples[i])
        sample_list.append(all_samples[i])

    g.plot_3d(sample_list,
                    ['log10xinj','log10G_X','log10f_dm'],
                    filled = [True,False],
                    colors = ['black','black'],
                    alphas = [0.3,0.7],
                   )

    g.export(path_to_figures+chains+'_3d.pdf')

<img width="518" alt="Screenshot 2020-10-26 at 15 16 15" src="https://user-images.githubusercontent.com/13769251/97218219-c60dd900-179e-11eb-979d-f152c1f06ea5.png">

**Comment by cmbant** [comment]
It may be easiest to do it using standard matplotlib on the subplots axes object.

**Comment by borisbolliet** [comment]
Ok, thank you, so here if I want to access, say the xaxis labels and ticks, what would be the syntax to access these in the plots.getSubplotPlotter()?

For instance, analogous to: 

ax.set_xticks([2,4,6,8,10])
ax.set_xlabels([‘two’, ‘four’,’six’, ‘eight’, ‘ten’])

Please ignore this if this is not straightforward,
I am also closing this as this is not really an issue...
Thanks a lot!
Boris

**Comment by cmbant** [comment]
you can use g.subplots[...,..] to get the ax object after making a getdist subplot array. Or use g.get_axes(param1,param2).
