### ISSUE TITLE
first_chain

### ISSUE THREAD

**Issue by eatdust** [cmbant/getdist#6]
Hi Antony,
just have an issue to read chains not starting at _1. I guess the fix is to change line 57 in chains.py:

 if index > 0 and not os.path.exists(fname) or 0 < last_chain < index: break

by

 if index > first_chain and not os.path.exists(fname) or 0 < last_chain < index: break

cheers,
chris

**Comment by cmbant** [comment]
I guess this is also a specific case where for some reason the earlier numbered chains don't actually exist. I've made the change to the devel branch, will appear in master at next merge. Thanks.
