### ISSUE TITLE
Is it possible to have horizontal marginalized 1D density?

### ISSUE THREAD

**Issue by gapplef** [cmbant/getdist#61]
First, thanks for this great package!

Recently, I have to plot figures similar to the following:
![Screenshot](https://user-images.githubusercontent.com/5604665/112637370-0cb04e00-8e79-11eb-91a0-9e219256c67a.png)

Note the marginalized 1D density on the right is horizontal-oriented, is it possible to achieve this with getdist?
I have read the docs but can't find the proper parameters to set.

**Comment by cmbant** [comment]
No (why not just use getdist's standard triangle plot instead).

**Comment by gapplef** [comment]
I would like to, but that's the requirement of my supervisor ...
Thanks for your quick response anyway.
