### ISSUE TITLE
densities: Array size mismatch

### ISSUE THREAD

**Issue by jacopo-chevallard** [cmbant/getdist#7]
Hi, perhaps you can help with the error below, that arises whenever the length of the ``bins`` array is larger than ``fine_bins``, in [these lines](https://github.com/cmbant/getdist/blob/a14cf5fb37d64764c919b3ec3c02ba3ebf6e6efb/getdist/mcsamples.py#L1269-L1301) of ``mcsamples.py``.

The cause of the error is that 1d-density is computed as
```python
density1D = Density1D(fine_x, P=conv, view_ranges=[par.range_min, par.range_max])
```
but ``conv`` and ``fine_x`` have different sizes in this scenario
```python
conv = convolve1D(bins, Kernel.Win, 'same', cache=cache)
fine_x = np.linspace(binmin, binmax, fine_bins)
``` 

Original error:

```
File "/Library/Python/2.7/site-packages/getdist/plots.py", line 1829, in triangle_plot
    label_right=True, no_zero=True, no_ylabel=True, no_ytick=True, line_args=line_args)
  File "/Library/Python/2.7/site-packages/getdist/plots.py", line 1299, in plot_1d
    bounds = self.add_1d(root, root_param, i, normalized=normalized, **line_args[i])
  File "/Library/Python/2.7/site-packages/getdist/plots.py", line 807, in add_1d
    density = self.sampleAnalyser.get_density(root, param, likes=self.settings.plot_meanlikes)
  File "/Library/Python/2.7/site-packages/getdist/plots.py", line 528, in get_density
    density = samples.get1DDensityGridData(name, meanlikes=likes)
  File "/Library/Python/2.7/site-packages/getdist/mcsamples.py", line 1297, in get1DDensityGridData
    density1D = Density1D(fine_x, P=conv, view_ranges=[par.range_min, par.range_max])
  File "/Library/Python/2.7/site-packages/getdist/densities.py", line 134, in __init__
    self.setP(P)
  File "/Library/Python/2.7/site-packages/getdist/densities.py", line 89, in setP
    raise DensitiesError("Array size mismatch in Density arrays: P %s, axis %s" % (size, ax.size))
getdist.densities.DensitiesError: Array size mismatch in Density arrays: P 1170, axis 200
```

**Comment by cmbant** [comment]
Thanks for the report, though I'm not sure I fully understand how to get it. Do you have a complete example to reproduce? (also welcome to make a pull request if you know how to fix)

**Comment by jacopo-chevallard** [comment]
I'm not sure how to fix it, but the problem is that the line
```python
bins = np.bincount(bin_indices, weights=self.weights, minlength=fine_bins)
```
produces a ``bin`` array with **minimum** length ``fine_bins``, but the length can also be > ``fine_bins`` (as in the case reported above), and the length of the ``bins`` array propagates to the shape of ``conv``
```python
conv = convolve1D(bins, Kernel.Win, 'same', cache=cache)
``` 
while the ``fine_x`` array has always **exact** length ``fine_bins``
```python
fine_x = np.linspace(binmin, binmax, fine_bins)
```
and so when we build a ``Density1D`` instance with the command
```python
 density1D = Density1D(fine_x, P=conv, view_ranges=[par.range_min, par.range_max])
```
we get the reported error, since ``conv`` and ``fine_x`` have incompatible dimensions.

**Comment by cmbant** [comment]
OK thanks. Do you have some code to reproduce the issue as a test case?

**Comment by jacopo-chevallard** [comment]
I can try to put something together, but it won't be immediate since I integrated ``getdist`` into a tool I developed to post-process the results of spectro-photometric SED fitting, so I would have to provide you the entire package...
Perhaps the easiest thing if that you test a modified ``mcsamples.py.``  with your standard test case, then upload it here (in the issue) and I test it in my case? 
If the modifications are simple enough and don't require too many iterations, then it should work...

**Comment by cmbant** [comment]
OK thanks, but it'll be hard to fix without being able to replicate it. Could you just dump out an offending chain to file and make a short simple example using that?

**Comment by jacopo-chevallard** [comment]
I know, I'm working with a collaborator on creating a MWE, hope to have soon news

**Comment by jacopo-chevallard** [comment]
thanks to @ACCarnall we have a MWE (see the attached archive) that you should be able to run with
```
python test.py
```
[error_example.zip](https://github.com/cmbant/getdist/files/539600/error_example.zip)

let us know if it works

**Comment by cmbant** [comment]
Are your formation_redshift ranges correct? The sample values seem to larger than the stated upper bound hard prior range.

**Comment by jacopo-chevallard** [comment]
@ACCarnall can you check in the input parameter file which range did you put for the ``formation_redshift``?

**Comment by ACCarnall** [comment]
Ah, thank you very much! Turns out the prior boundary was 50 and the upper bound I put in the parameter file was only 10. Things appear to work fine once this is rectified.

**Comment by jacopo-chevallard** [comment]
Excellent, thanks for the hint Antony! I don't know if it can be useful to insert a more explicit error message (e.g. bound checking) for these situations, I'll let you decide and close the issue

**Comment by cmbant** [comment]
In a commit last week I did a check on positivity of the range.
