### ISSUE TITLE
getdist vs montepython analyze module for montepython chains with --update

### ISSUE THREAD

**Issue by Ferrangelo** [cmbant/getdist#70]
Hi everyone. When running montepython with the `--update` or `--superupdate` options active we want to analyze only the part of the chain after the last covariance matrix or jumping factor updates. The montepython analyze module does that automatically, it says 

> The Markovian properties of the MCMC are maintained by the MontePython analyze module, which will only analyze steps after the last covariance matrix update. 

Does getdist do that automatically as well when I analyze montepython chains with it? If not, are there options I can switch on to let getdist do this?

**Comment by cmbant** [comment]
No, but you can manually filter chain arrays as you like before sending the samples you want to getdist. Cobaya outputs continuous chains, usually dropping the first 1/3 is enough to avoid burn in and convariance learning  (non-Markovian updates are OK once the covariance itself has converged).

**Comment by Ferrangelo** [comment]
Thank you for the clear and very fast answer
