### ISSUE TITLE
Plotting questions

### ISSUE THREAD

**Issue by emilymmoser** [cmbant/getdist#71]
Hello, 

I have a question regarding the title_limit option, and a follow up question regarding legends if there isn't a solution for the first. 

1. Is it possible to either display the marginalized constraint for multiple roots, or select a specific root to display? I realize it displays the tex for the first given root and I could simply change the order, however I have a case with a large contour that would cover the smaller contours if not plotted first, regardless of changing the alpha parameters.

![test_corner_2d](https://user-images.githubusercontent.com/42976886/131918514-7c76bf6e-259e-4c44-83c5-386c2507c567.png)

In short, I'm trying to display the tex for the blue contours, which are the smallest in size, so I can't simply change it to be plotted first. Perhaps there's a zorder kwarg that could also solve this?

2. If there isn't a simple solution to the above, I have also used plot_1d to only plot the 1D distributions, where I can more freely change around the plotting order. First, when I use the legend keywords within the g.plot_1d() function it returns a legend that overlaps the tex, see below:

![test_corner_1d_1legend_overlap](https://user-images.githubusercontent.com/42976886/131919320-24f52b6d-56c7-4d5e-914b-0248316fcce0.png)

Then I tried to more manually add the legend using g.add_legend, and specify a location using bbox_to_anchor. But it seems the g.plot_1d function still plots a legend, resulting in two different legends (see figure below)

![test_corner_1d_2legend](https://user-images.githubusercontent.com/42976886/131919548-31aa8e1e-e4cd-4baf-8869-da486cc5e21b.png)

Is there an option to not show a legend from plot_1d, and only the "manually added" one from add_legend? 

I apologize if these are trivial questions, and thank you in advance for your time.

**Comment by cmbant** [comment]
Try setting settings.constrained_layout=True for legend. For ordering you're welcome to make a pull request adding the option. (general questions not related to bugs or pull requests should be posted on CosmoCoffee).

**Comment by emilymmoser** [comment]
Sorry about that, I wasn't aware of CosmoCoffee. 
Constrained layout did not work as hoped, but perhaps I will make a new post there. Thank you again for your help.
