### ISSUE TITLE
`getdist-gui` fails with secondary monitor

### ISSUE THREAD

**Issue by lukashergt** [cmbant/getdist#76]
## Description

When I run `getdist-gui` it works with a single monitor setup, but fails with dual monitor setup. 

Did anybody else encounter this before? 
Any ideas how I could fix this (without the need of disconnecting the secondary screen)?

(It might be that this has to do with my i3 tiling window manager setup, though...)

## Setup

```
GetDist                  1.3.3
PySide2                  5.15.2.1
shiboken2                5.15.2.1
```

## Error message

```
(py310env) [~]$ getdist-gui
Traceback (most recent call last):
  File "/home/lukas/.virtualenv/py310env/bin/getdist-gui", line 8, in <module>
    sys.exit(getdist_gui())
  File "/home/lukas/.virtualenv/py310env/lib/python3.10/site-packages/getdist/command_line.py", line 355, in getdist_gui
    run_gui()
  File "/home/lukas/.virtualenv/py310env/lib/python3.10/site-packages/getdist/gui/mainwindow.py", line 2333, in run_gui
    mainWin = MainWindow(app, ini=args.ini, plot_scale=args.plot_scale)
  File "/home/lukas/.virtualenv/py310env/lib/python3.10/site-packages/getdist/gui/mainwindow.py", line 139, in __init__
    self._createWidgets()
  File "/home/lukas/.virtualenv/py310env/lib/python3.10/site-packages/getdist/gui/mainwindow.py", line 604, in _createWidgets
    self.readSettings()
  File "/home/lukas/.virtualenv/py310env/lib/python3.10/site-packages/getdist/gui/mainwindow.py", line 618, in readSettings
    screen = self.getScreen()
  File "/home/lukas/.virtualenv/py310env/lib/python3.10/site-packages/getdist/gui/mainwindow.py", line 614, in getScreen
    return QApplication.screenAt(self.mapToGlobal(QPoint(self.width() / 2, 0))).availableGeometry()
AttributeError: 'NoneType' object has no attribute 'availableGeometry'
```

## Problem

[`screenAt(point)`](https://doc.qt.io/qtforpython-5/PySide2/QtGui/QGuiApplication.html#PySide2.QtGui.PySide2.QtGui.QGuiApplication.screenAt) is supposed to return the screen at `point`, or `None` if outside of any screen, so here it clearly is pointing outside a screen. 

## ugly fix

Disconnect the secondary screen, then launch `getdist-gui`. You can reconnect the secondary screen afterwards.

**Comment by cmbant** [comment]
Not sure, was your window very wide or something? Does it work with QApplication.screenAt(self.mapToGlobal(QPoint(0,0)))?

**Comment by lukashergt** [comment]
> Does it work with QApplication.screenAt(self.mapToGlobal(QPoint(0,0)))?

No, `(0, 0)` didn't work either, but I tried a bit more and I think I know now what happens. My secondary screen has a better resolution than my primary screen and I aligned them at the bottom edge, while the `(0, 0)` point is in the top left corner and points to empty space:

```
(0,0)
  · · · · · · · · · · · · · · · |--------------------------------------|
  ·                             |                                      |
  ·          (empty)            |                                      |
  ·                             |                                      |
  ------------------------------|                                      | 1
  |                             |              (secondary)             | 4
1 |                             |                                      | 4
0 |         (primary)           |                                      | 0
8 |                             |                                      |
0 |                             |                                      |
  |                             |                                      |
  ----------------------------------------------------------------------
             1920                               2560
```

I have to increase the `y` value to hit the primary screen, e.g.:
```
QApplication.screenAt(self.mapToGlobal(QPoint(0, 1440)))
```
where I used the y-resolution of my secondary screen as y-input.

Not sure whether there might be a good generalised implementation to make this run robustly on all sorts of setups (happy to test things out), or whether this is too specific to my setup. Anyhow, this is a much nicer solution than constantly disconnecting my secondary screen, so I'm happy to implement this locally (i.e. happy for this issue to be closed). Maybe this proves useful to someone else, too.

Thanks, Antony!

**Comment by cmbant** [comment]
Looks like a bug in qt/pyside to me, maptoglobal is supposed to map from the current widget so 0,0 should always work

https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QWidget.html#PySide2.QtWidgets.PySide2.QtWidgets.QWidget.mapToGlobal

**Comment by lukashergt** [comment]
Hmm, but `mapToGlobal` works, it is `screenAt(0, 0)` that returns `None` when `(0, 0)` points off-screen, which can happen with dual monitor setup.

Why not change the whole method from:
```python
    def getScreen(self):
        return self.screenAt(self.mapToGlobal(QPoint(self.width() / 2, 0))).availableGeometry()
```
to:
```python
    def getScreen(self):
        return self.screen().availableGeometry()
```

That works for me out of the box and seems a lot less complicated than using `screenAt`.

**Comment by cmbant** [comment]
On my system self.screen() give
`
AttributeError: 'MainWindow' object has no attribute 'screen'`

Shouldn't matToGlobal not return (0,0) but the actual valid global coordinate of the window position?

**Comment by lukashergt** [comment]
[`MainWindow`](https://github.com/cmbant/getdist/blob/529db7ce1e1abe8e672cbfa5363af532295b2fb8/getdist/gui/mainwindow.py#L112) is inheriting from [`QMainWindow`](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QMainWindow.html) which in turn inherits from [`QWidget`](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QWidget.html) which should have a method [`screen()`](https://doc.qt.io/qtforpython-5/PySide2/QtWidgets/QWidget.html#PySide2.QtWidgets.PySide2.QtWidgets.QWidget.screen). 

This should at least be the case for newer versions of PySide2. I've used version 5.15.2. [`QWidget` in version 5.12.3](https://doc.qt.io/archives/qtforpython-5.12/PySide2/QtWidgets/QWidget.html#qwidget) indeed does not have the method `screen`.

**Comment by cmbant** [comment]
I tried putting in an except block with fallback to original code:
https://github.com/cmbant/getdist/commit/8d16213353d6dd9dc92c2df342f27098f43ab1a4

**Comment by lukashergt** [comment]
Great, thanks Antony!
