### ISSUE TITLE
title_limit different than MargeStats ?

### ISSUE THREAD

**Issue by olakusiak** [cmbant/getdist#77]
Hi,

is it possible that the values for marginalized limits are different when obtained with _samps.getMargeStats()_ versus the onesquoted on a triangle plot when setting 'title_limit' to the desired value (in this case I'm looking at 68%, so title_limit=1). This is what's happening to me when looking at some chains generated by cobaya. 

I can see that title_limit calls a function _getInlineLatex()_, which then uses _texValues()_, and I believe this function is giving me different limits than the ones from margestats.

**Comment by cmbant** [comment]
Don't think so, if settings when calculated are the same. Specific example?

**Comment by olakusiak** [comment]
On the screenshot I am showing 

1) the output of the getInlineLatex() function, with title_limit=1 (so 68%) for one of my parameters, which is what is also shown on on my triangle plots

2) the output of the Margestat for the same parameter. I highlighter what's supposed to correspond to mean, std, the lower 68%limit (as I understand it),and the upper 68%. 

You can see that the getInlineLatex quotes some other limits, which are closer to the std, but also not exactly. 
Am I missing something very obvious here? 

Thank you.

<img width="1103" alt="github" src="https://user-images.githubusercontent.com/62485729/152998342-424fa9b6-f5d6-4e5b-ae03-cce60b52af10.png">

**Comment by cmbant** [comment]
Looks consistent to me:
```
1.3753-1.2587=0.1166 \approx 0.12
1.4649-1.375=0.0.899 \approx 0.09

```

**Comment by olakusiak** [comment]
oh, I got confused because I thought what's in margestats under lower1 and upper1 is supposed to be equal to the difference (\pm) values . But that of course makes sense now, thank you
