### ISSUE TITLE
No proper error message

### ISSUE THREAD

**Issue by nilay121** [cmbant/getdist#78]
Not getting any error message when we pass a numpy array having strings of number to the MCSamples() class. The functions goes in an infinite loop and never terminates

**Comment by cmbant** [comment]
Reproducing code please
________________________________
From: NILAY KUSHAWAHA ***@***.***>
Sent: Thursday, February 17, 2022 7:53:26 AM
To: cmbant/getdist ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cmbant/getdist] No proper error message (Issue #78)


Not getting any error message when we pass a numpy array having strings of number to the MCSamples() class. The functions goes in an infinite loop and never terminates

**Comment by nilay121** [comment]
![error](https://user-images.githubusercontent.com/40202640/154449572-0159de2a-46c3-4476-8631-17baa510f3c8.png)
![error2](https://user-images.githubusercontent.com/40202640/154449583-803d1a4e-da80-4efb-a49e-7cffc439c374.png)

The code should throw some error if we give a string to the MCSamples() class but rather it keeps on running the cell forever, and we need to manually interrupt the execution

**Comment by cmbant** [comment]
OK thanks. This looks like a fairly obscure user error, but you are welcome to make a pull request with extra error handling.

**Comment by nilay121** [comment]
Thanks for your reply, I will try it.
