### ISSUE TITLE
Plotting multiple 3d scatter plots

### ISSUE THREAD

**Issue by Jasonpoh** [cmbant/getdist#79]
I was wondering if it's possible to plot multiple 3D scatter plots on the same triangle plot? 

For example, like this:
![image](https://user-images.githubusercontent.com/17857920/158637736-a9a4cecd-009b-4147-9ab5-876b550f59e8.png)

but with 2 color maps and 2 scatter plots (instead of 1 scatter plot and 1 contour plot as shown in the image)

**Comment by cmbant** [comment]
Not something that's supported out of the box.
