### ISSUE TITLE
Get statistics for a fixed value of an originally varied parameter

### ISSUE THREAD

**Issue by bhorowitz** [cmbant/getdist#8]
Lets say I have a MCMC output chain for varied parameter X1,...,XN. Is there currently a way to look at the distributions and statistics for the other parameters given  fixed value of parameter Xi? I.e. if I run cosmomc for all cosmic parameters but I want to look at the case where I fix H0 at a certain values. It seems like there should be enough information in the overall chain to do this without having to run MCMC again given a fixed H0?

**Comment by cmbant** [comment]
There isn't enough information to do this properly - there will be essentially zero samples at any given value of H0. Best you can do it importance sample a tight prior around the value of H0 of interest (assuming there are plenty of samples in that H0 region).

**Comment by bhorowitz** [comment]
Right, but doesn't the code essentially take a KDE of the imported distribution? At this point can we not work in the "KDE-space" and select a cut at constant H0 without having to go back to the original chain? More abstractly I'm visualizing the KDE process as essentially creating a "smooth" N-dimensional surface, which we can then take a cross-sectional at constant H0 to yield an (N-1)D subsurface.

**Comment by cmbant** [comment]
KDE only really works in 1 or 2D, unless you have an exponentially large number of samples.
