### ISSUE TITLE
contour_lws and lws are both controlling linewidths of 1-d marginalized plots

### ISSUE THREAD

**Issue by ctrendafilova** [cmbant/getdist#81]
I am plotting a 2-d triangle plot, and I would like to change the line widths of the 2-d contours, specifically. I would think lws and contour_lws are supposed to work analogously to colors and contour_colors, where one parameter controls the 1-d curves and the other controls the 2-d contours. However, both lws and contour_lws are changing the width of the curves in the 1-d panels while leaving the 2-d contours unchanged.

As an example, this behavior can be seen in the example plot_gallery.html, in the third figure of In[19].

**Comment by cmbant** [comment]
I think it works with unfilled contours. Welcome to make a PR to also support filled if you like.
