### ISSUE TITLE
800 GB on getdist cache

### ISSUE THREAD

**Issue by vivianmiranda** [cmbant/getdist#85]
Hi Lewis,

I hope you are well. I am writing because my server just crashed with my OS hard drive being out of space. After investigation, I noticed that ~/.cache/getdist_cache/ was consuming 800GB! Is it possible to make GetDist not use so much cache memory? Getdist will always crash OS drives  (which are not usually large) with such behavior. 

Best
Vivian

**Comment by cmbant** [comment]
I guess this is on linux. The idea is that this location is a directory that is automatically purged periodically or when space is needed. On linux systems it comes from the XDG_CACHE_HOME cache env var if set. Welcome to suggest improvements to getdist's _get_cache_dir function.

**Comment by cmbant** [comment]
any suggestions for improvement on this or can I close?

**Comment by cmbant** [comment]
Closing as no response
