### ISSUE TITLE
Legend when just one 2D-plot

### ISSUE THREAD

**Issue by vittoriodx7** [cmbant/getdist#86]
Hi,
first of all thanks for creating this awesome package.
I want to ask for support when creating legend object for a plot_2d when I add a user defined line.
Let say that I am creating first an MCSamples object from my data:
```
mcsamples = MCSamples(
        samples = data,
        names = labels,
        labels = labels,
        weights = None,
        label = 'My data'
)
```
and then I make a 2D plot out from sample a and b:
```
g = plots.get_subplot_plotter(width_inch = 14)
g.plot_2d(mcsamples, 'a', 'b', filled = True, contour_colors = 'C0')

```
and now I add a user defined line to the plot
`l1 = g.subplots[0,0].plot(x, y, color = 'C1', label = 'Line label')`
(I don't know if it is the best way to do so. But `g.subplots[0,0]` can be treated like a normal matplotlib axes, so I do that)
Finally I would like to add a legend to this plot that shows both 'My data' and 'Line label'. However when I try to use standard matplotlib 
`g.subplots[0,0].legend()`
I see only 'Line label'.

I think the issue might be to the fact that getdist creates two legend objects: figure_legend and ax_legend. However in a single plot_2d would be nice if there was a nice way of adding the first to the latter so the two legends would be merged.
At the moment the only way I found is to manually create a new artist and adding that to the current axis.
```
mylegend = g.subplots[0, 0].legend([g.contours_added[0], l1[0]], [mcsamples.getLabel(), l1[0]._label], fontsize = 30)
g.subplots[0, 0].add_artist(mylegend)
```
But I was wondering if there was a better option. 
Thanks

![Screenshot_20221029_085456](https://user-images.githubusercontent.com/50493608/198819032-7a0826df-5e02-4274-bd76-f79e9a7833d9.png)

**Comment by cmbant** [comment]
Not an easier option that I can immediately think of
