### ISSUE TITLE
Plot density instead of contours in 2D plots

### ISSUE THREAD

**Issue by mraveri** [cmbant/getdist#88]
Is it possible to plot density instead of contours in 2D plots?
Also, is it possible to add 1D "contours" (i.e. confidence intervals) to 1D plots as well?

Happy to open a PR implementing this if not!

**Comment by cmbant** [comment]
You can use the [shaded](https://getdist.readthedocs.io/en/latest/plots.html#getdist.plots.GetDistPlotter.plot_2d) option to colour by the density. It does also plot the contours, but I guess you could make them invisible. 
title_limit will print the confidence limit over each plot, but no specific option to add lines at the limits.

**Comment by mraveri** [comment]
This would not allow overlaying though?

This would be achievable taking the color associated to the chain and creating a colormap that sweeps linearly to alpha=0 (starting from the user-provided alpha value)

Do you think it would be a good idea to add something like this?

- “shaded=False" option in 2D plots -> “density=False" option (plots density), new option “contours=True” plots contours
- 1D plots “contours=False” plots lines showing CLs, “filled=False” fills them up (useful for multi-modal)

I am working on an application where something like this would be useful...

**Comment by cmbant** [comment]
Currently, you can plot multiple contours with shaded, but only the first is shaded  (all show contour lines). I would have thought multiple shadings in different colours would often be very hard to see/interpret when they overlap?

Would have to think about how any new argument names interact/conflict with those also for higher level triangle_plot etc.

shaded currently plots the density or mean likelihood, depending on the global setting, so not always a density.

For 1D, limit_markers or something might be more consistent with current terminology ("marker" is used for vertical lines at a value)
