### ISSUE TITLE
Problem with GUI

### ISSUE THREAD

**Issue by matteotagliazucchi** [cmbant/getdist#89]
I've just installed getdist with the usual command `pip install getdist`.
However, running `getdist-gui` gives the error
```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Aborted (core dumped)
```
I've searched the internet and tried some solutions, but nothing worked.

EDIT:
The problem disappears in new virtual environment. 
Probably there are dependence problems in my pc.
However, even in the new virtual environment, I get the error  `AttributeError: 'RootListWidget' object has no attribute 'InternalMove'` when I run `getdist-gui`.

**Comment by cmbant** [comment]
Sounds like a problem with pyside/QT installation, rather than specific to getdist

**Comment by matteotagliazucchi** [comment]
> Sounds like a problem with pyside/QT installation, rather than specific to getdist

You're right. Indeed, in a virtual environment the package works fine.
However, there are still problems with the gui.
In particular, if I run `getdist-gui` I get the error `AttributeError: 'RootListWidget' object has no attribute 'InternalMove'`.

**Comment by cmbant** [comment]
I've heard that one before - not sure what causes it, but just try commenting out the offending line?

**Comment by matteotagliazucchi** [comment]
> I've heard that one before - not sure what causes it, but just try commenting out the offending line?

It worked!
Thank you so much

**Comment by matteotagliazucchi** [comment]
> I've heard that one before - not sure what causes it, but just try commenting out the offending line?
