### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by JunHuiLiu2017** [cmbant/getdist#91]
Hi.
I just copy the sample from the website "https://getdist.readthedocs.io/en/latest/plot_gallery.html" to the Pycharm on my MacBook pro with M2 core. But an error occurred when it runs to 
"g = plots.get_subplot_plotter()
g.triangle_plot([samples, samples2], filled=True)" .

The error is :
/Users/miniforge3/envs/test_tf/bin/python3.9 /Users/PycharmProjects/LamostBinary/src/test.py
GetDist Version: 1.4, Matplotlib version: 3.5.2
Removed no burn in
Removed no burn in
Exception ignored in: <function GetDistPlotter.__del__ at 0x159e673a0>
Traceback (most recent call last):
  File "/Users/liujunhui/miniforge3/envs/test_tf/lib/python3.9/site-packages/getdist/plots.py", line 726, in __del__
  File "/Users/liujunhui/miniforge3/envs/test_tf/lib/python3.9/site-packages/getdist/_base.py", line 38, in __getattribute__
TypeError: 'NoneType' object is not callable

Thank you.

**Comment by cmbant** [comment]
Weird, does it work outside PyCharm (I think they did introduce a few debugging oddities in a recent update). Hard to see how "_map_name" could be None, given the function is defined in the same file just above. It works OK in pycharm for me though.

**Comment by cmbant** [comment]
Could be some python library bug I guess. Does it work if you comment out the __del__ function? Could try a clean python 10 or 11 environment.

**Comment by cmbant** [comment]
Closing absent any further information
